import { ReactNode } from 'react'
import Head from 'next/head'
import Navbar from './Navbar'
import Footer from './Footer'
import { Container, Flex } from '@chakra-ui/react'

function Layout({title, children}: {title: string, children: ReactNode}) {
  return (
      <>
        <Head>
          <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Container as={'main'} mt={'16'} maxW='container.lg' centerContent minH={'100vh'}>
          {children}
        </Container>
        <Footer />
      </>
  )
}

export default Layout